CREATE TABLE IF NOT EXISTS public.nhucauvanchuyen
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL DEFAULT auth.uid(),
    anh1 character varying COLLATE pg_catalog."default",
    anh2 character varying COLLATE pg_catalog."default",
    anh3 character varying COLLATE pg_catalog."default",
    anh4 character varying COLLATE pg_catalog."default",
    anh5 character varying COLLATE pg_catalog."default",
    anh6 character varying COLLATE pg_catalog."default",
    anh7 character varying COLLATE pg_catalog."default",
    anh8 character varying COLLATE pg_catalog."default",
    anh9 character varying COLLATE pg_catalog."default",
    mota text COLLATE pg_catalog."default",
    matinhxuatphat character varying COLLATE pg_catalog."default",
    matinhdich character varying COLLATE pg_catalog."default",
    kichthuoc text COLLATE pg_catalog."default",
    trongluong text COLLATE pg_catalog."default",
    CONSTRAINT nhucauvanchuyen_pkey PRIMARY KEY (id)
)