CREATE TABLE IF NOT EXISTS public.thongtinxe
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL DEFAULT auth.uid(),
    email character varying COLLATE pg_catalog."default" NOT NULL,
    anh1 character varying COLLATE pg_catalog."default",
    anh2 character varying COLLATE pg_catalog."default",
    anh3 character varying COLLATE pg_catalog."default",
    anh4 character varying COLLATE pg_catalog."default",
    anh5 character varying COLLATE pg_catalog."default",
    anh6 character varying COLLATE pg_catalog."default",
    anh7 character varying COLLATE pg_catalog."default",
    anh8 character varying COLLATE pg_catalog."default",
    anh9 character varying COLLATE pg_catalog."default",
    matinh character varying COLLATE pg_catalog."default",
    tentinh_tienganh character varying COLLATE pg_catalog."default",
    tentinh_tiengviet character varying COLLATE pg_catalog."default",
    tentinh_tiengthai character varying COLLATE pg_catalog."default",
    temtinh_tiengtrung character varying COLLATE pg_catalog."default",
    maquan character varying COLLATE pg_catalog."default",
    tenquan_tienganh character varying COLLATE pg_catalog."default",
    tenquan_tiengviet character varying COLLATE pg_catalog."default",
    tenquan_tiengthai character varying COLLATE pg_catalog."default",
    tenquan_tiengtrung character varying COLLATE pg_catalog."default",
    diachichitiet character varying COLLATE pg_catalog."default",
    bienso character varying COLLATE pg_catalog."default",
    maloaixe character varying COLLATE pg_catalog."default",
    tenloaixe_tienganh character varying COLLATE pg_catalog."default",
    tenloaixe_tiengviet character varying COLLATE pg_catalog."default",
    tenloaixe_tiengtrung character varying COLLATE pg_catalog."default",
    tenloaixe_tiengthai character varying COLLATE pg_catalog."default",
    taitrong_tan numeric,
    taitrong_m3 numeric,
    kichthuoccont character varying COLLATE pg_catalog."default",
    CONSTRAINT thongtinxe_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.thongtinxe
    OWNER to postgres;

ALTER TABLE IF EXISTS public.thongtinxe
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.thongtinxe TO anon;

GRANT ALL ON TABLE public.thongtinxe TO authenticated;

GRANT ALL ON TABLE public.thongtinxe TO postgres;

GRANT ALL ON TABLE public.thongtinxe TO service_role;
-- POLICY: Enable insert for authenticated users only

-- DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.thongtinxe;

CREATE POLICY "Enable insert for authenticated users only"
    ON public.thongtinxe
    AS PERMISSIVE
    FOR INSERT
    TO authenticated
    WITH CHECK (true);
-- POLICY: Enable read access for all users

-- DROP POLICY IF EXISTS "Enable read access for all users" ON public.thongtinxe;

CREATE POLICY "Enable read access for all users"
    ON public.thongtinxe
    AS PERMISSIVE
    FOR SELECT
    TO authenticated
    USING (true);
-- POLICY: Enable update for users based on email

-- DROP POLICY IF EXISTS "Enable update for users based on email" ON public.thongtinxe;

CREATE POLICY "Enable update for users based on email"
    ON public.thongtinxe
    AS PERMISSIVE
    FOR UPDATE
    TO authenticated
    USING (((( SELECT auth.jwt() AS jwt) ->> 'email'::text) = (email)::text))
    WITH CHECK (((( SELECT auth.jwt() AS jwt) ->> 'email'::text) = (email)::text));